// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6TFPS9cj43HEpoROQOXgKkLBOq7iThI',
    appId: '1:432041123207:web:fe6d0f7d32cb27866c4722',
    messagingSenderId: '432041123207',
    projectId: 'nerobot-40a73',
    authDomain: 'nerobot-40a73.firebaseapp.com',
    storageBucket: 'nerobot-40a73.appspot.com',
    measurementId: 'G-465M6GPKQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtbGcw9SnBB965SA2_zrbGCovBMc76m4',
    appId: '1:432041123207:android:1d66cf7c7cf9d27e6c4722',
    messagingSenderId: '432041123207',
    projectId: 'nerobot-40a73',
    storageBucket: 'nerobot-40a73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7T9f1qwbfl--7ZA_xCY18eI5N3anx8Wk',
    appId: '1:432041123207:ios:b9ab6bb3ee6f2a0b6c4722',
    messagingSenderId: '432041123207',
    projectId: 'nerobot-40a73',
    storageBucket: 'nerobot-40a73.appspot.com',
    androidClientId: '432041123207-75lpc56ooa08b1to53kg2cs15dp44sii.apps.googleusercontent.com',
    iosBundleId: 'com.nerobot.app.nerobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7T9f1qwbfl--7ZA_xCY18eI5N3anx8Wk',
    appId: '1:432041123207:ios:b9ab6bb3ee6f2a0b6c4722',
    messagingSenderId: '432041123207',
    projectId: 'nerobot-40a73',
    storageBucket: 'nerobot-40a73.appspot.com',
    androidClientId: '432041123207-75lpc56ooa08b1to53kg2cs15dp44sii.apps.googleusercontent.com',
    iosBundleId: 'com.nerobot.app.nerobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn6TFPS9cj43HEpoROQOXgKkLBOq7iThI',
    appId: '1:432041123207:web:24028ce7596ca21f6c4722',
    messagingSenderId: '432041123207',
    projectId: 'nerobot-40a73',
    authDomain: 'nerobot-40a73.firebaseapp.com',
    storageBucket: 'nerobot-40a73.appspot.com',
    measurementId: 'G-KFQ6ZMV3BF',
  );
}
